const baseUrl = "https://shive.atelier-team.ir/apiv1/";
export const LOGIN = baseUrl + "login/";
export const SIGNUP = baseUrl + "signup/";
export const TEAMS_LIST = baseUrl + "team/list/";
export const TEAMS_DELETE = baseUrl + "team/delete/";
export const TEAMS_EDIT = baseUrl + "team/edit/";
export const TEAMS_CREATE = baseUrl + "team/create/";
export const GET_PENDING_PERSON = baseUrl + "profile/list/pending/"
export const ACCEPT_PENDING_PERSON = baseUrl + "profile/accept/"
export const REJECT_PENDING_PERSON = baseUrl + "profile/reject/"
export const CREATE_SUBJECT = baseUrl + "subject/create/"
export const GET_ALL_SUBJECT = baseUrl + "subject/list/all/"
export const UPDATE_SUBJECT = baseUrl + "subject/update/"
export const DELETE_SUBJECT = baseUrl + "subject/delete/"